// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NewCalculateTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void newCalculateTest() {
    driver.get("https://www.calculator.net/calorie-calculator.html");
    vars.put("VarGender", "F");
    if ((Boolean) js.executeScript("return (arguments[0]===\'F\')", vars.get("VarGender"))) {
      driver.findElement(By.cssSelector("td > .cbcontainer:nth-child(2) > .rbmark")).click();
      driver.findElement(By.id("cactivity")).click();
      {
        WebElement dropdown = driver.findElement(By.id("cactivity"));
        dropdown.findElement(By.xpath("//option[. = 'Very Active: intense exercise 6-7 times/week']")).click();
      }
      driver.findElement(By.id("cactivity")).click();
      {
        WebElement dropdown = driver.findElement(By.id("cactivity"));
        dropdown.findElement(By.xpath("//option[. = 'Active: daily exercise or intense exercise 3-4 times/week']")).click();
      }
    } else {
      driver.findElement(By.id("cactivity")).click();
      {
        WebElement dropdown = driver.findElement(By.id("cactivity"));
        dropdown.findElement(By.xpath("//option[. = 'Very Active: intense exercise 6-7 times/week']")).click();
      }
    }
  }
}
