// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchSamsungTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchSamsung() {
    driver.get("https://www.amazon.in/");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.id("twotabsearchtextbox")).click();
    driver.findElement(By.id("twotabsearchtextbox")).sendKeys("samsung");
    driver.findElement(By.id("twotabsearchtextbox")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Best Sellers")).click();
    driver.findElement(By.linkText("Bags, Wallets and Luggage")).click();
    driver.findElement(By.cssSelector("#nav-cart-text-container > .nav-line-2")).click();
    driver.findElement(By.id("nav-your-amazon-text")).click();
    driver.findElement(By.linkText("Mobiles")).click();
    driver.findElement(By.id("nav-cart-count")).click();
    {
      WebElement element = driver.findElement(By.id("nav-link-accountList-nav-line-1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("nav-link-accountList-nav-line-1")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".icp-nav-link-inner"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
